name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  APP_NAME: Raincoat

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "21"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > keystore.jks

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/apk/release/app-release.apk ${{ secrets.KEY_ALIAS }}

      - name: Verify APK
        run: jarsigner -verify -verbose -certs app/build/outputs/apk/release/app-release.apk

      - name: Zipalign APK
        run: |
          $ANDROID_HOME/build-tools/33.0.0/zipalign -v 4 \
          app/build/outputs/apk/release/app-release.apk \
          app/build/outputs/apk/release/app-release-signed-aligned.apk

      - name: Get Version Name
        id: get_version
        run: echo "VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk '{print $3}' | tr -d '"')" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release-signed-aligned.apk app/build/outputs/apk/release/${{ env.APP_NAME }}-v${{ steps.get_version.outputs.VERSION_NAME }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-v${{ steps.get_version.outputs.VERSION_NAME }}
          path: android/app/build/outputs/apk/release/${{ env.APP_NAME }}-v${{ steps.get_version.outputs.VERSION_NAME }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/release/${{ env.APP_NAME }}-v${{ steps.get_version.outputs.VERSION_NAME }}.apk
          tag_name: v${{ steps.get_version.outputs.VERSION_NAME }}
          name: ${{ env.APP_NAME }} v${{ steps.get_version.outputs.VERSION_NAME }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
